CREATE TABLE PACIENT 
(	
	ID NUMBER(11,0) NOT NULL ENABLE, 
	FIRSTNAME VARCHAR2(40 BYTE), 
	LASTNAME VARCHAR2(40 BYTE), 
	EMAIL VARCHAR2(40 BYTE), 
	PHONE VARCHAR2(40 BYTE), 
	PERSONAL_ID VARCHAR2(10 BYTE), 
	BIRTHDATE DATE, 
	CONSTRAINT PACIENT_PK PRIMARY KEY (ID)
);