CREATE TABLE DIAGNOSTIC 
(
	ID NUMBER(11,0) NOT NULL ENABLE, 
	NAME VARCHAR2(40 BYTE), 
	DESCRIPTION VARCHAR2(100 BYTE), 
	SOLUTION VARCHAR2(100 BYTE), 
	CONSTRAINT DIAGNOSTICS_PK PRIMARY KEY (ID)
);
