CREATE TABLE SPECIALIZATION 
(	
    ID NUMBER(11,0) NOT NULL ENABLE, 
    DESCRIPTION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    CREATED_DATE DATE NOT NULL ENABLE, 
    CONSTRAINT SPECIALIZATION_PK PRIMARY KEY (ID)
 );