CREATE TABLE APPOINTMENT 
(	
	ID NUMBER(11,0) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(200 BYTE), 
	APPOINTMENT_DATE DATE, 
	USER_ID NUMBER(11, 0), 
	PACIENT_ID NUMBER(11, 0), 
	CONSTRAINT APPOINTMENT_PK PRIMARY KEY (ID),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID)  REFERENCES STAFF (ID) ENABLE, 
	CONSTRAINT PACIENT_ID_FK FOREIGN KEY (PACIENT_ID) REFERENCES PACIENT (ID) ENABLE
) ;
