CREATE TABLE STAFF 
(	
	ID NUMBER(11,0) NOT NULL ENABLE, 
	FIRSTNAME VARCHAR2(40 BYTE), 
	LASTNAME VARCHAR2(40 BYTE), 
	ROLE_ID NUMBER(11, 0),  
	EMAIL VARCHAR2(40 BYTE), 
	PASSWORD VARCHAR2(96 BYTE), 
	NOTIFICATION NUMBER (*,0),
	CONSTRAINT STAFF_ID_PK PRIMARY KEY (ID),
	CONSTRAINT ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE (ID) ENABLE
);